default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "" } %>
  username: <%= ENV.fetch("DB_USER") { "" } %>
  password: <%= ENV.fetch("DB_PASS") { "" } %>
  port: <%= ENV.fetch("DB_PORT") { "" } %>
  host: <%= ENV.fetch("DB_HOST") { "" } %>
test:
  <<: *default
  database: <%= ENV.fetch("TEST_DB_NAME") { "" } %>
  username: <%= ENV.fetch("DB_USER") { "" } %>
  password: <%= ENV.fetch("DB_PASS") { "" } %>
  port: <%= ENV.fetch("DB_PORT") { "" } %>
  host: <%= ENV.fetch("DB_HOST") { "" } %>
production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "" } %>
  username: <%= ENV.fetch("DB_USER") { "" } %>
  password: <%= ENV.fetch("DB_PASS") { "" } %>
  port: <%= ENV.fetch("DB_PORT") { "" } %>
  host: <%= ENV.fetch("DB_HOST") { "" } %>
